server:
  port: 8000
spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    #向注册中心注册IP
    prefer-ip-address: true
    #appname:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
info:
  description: 网关
zuul:
  retryable: true
  routes:
    dcim-energy-provider: /energy-service/**
    dcim-workflow-provider: /workflow-service/**
    dcim-alarm-provider: /alarm-service/**
    websocket-provider: /websocket-service/**
    dcim-asset-provider: /asset-service/**
    dcim-monitor-provider: /monitor-service/**
    dcim-capacity-provider: /capacity-service/**
    dcim-operatelog-provider: /operatelog-service/**
    dcim-systemmanage-provider: /userinfo-service/**
    dcim-data-query-provider: /data-query-service/**
    dcim-sms-provider: /sms-service/**
    dcim-quartz-provider: /quartz-service/**
    dcim-auth-server:
      path: /auth-service/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: dcim-auth-server
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitive-headers:
