server:
  port: 8093
spring:
  application:
    name: study-springboot
  messages:
    basename: i18n/messages
    encoding: UTF-8

# 自定义的一些属性
user:
  info:
    name: tuacy
    age: 27
email:
  send-email: 123@qq.com
  send-password: 123456
